version: 2.1
orbs:
  codecov: codecov/codecov@3
executors:
  docker-executor:
    docker:
      - image: cimg/node:lts-browsers

jobs:
  build:
    executor: docker-executor
    environment:
      LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          command: |
            node -v
            npm -v
            yarn -v
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Run Tests
          command: yarn run ci:test
      - codecov/upload
      - store_artifacts:
          path: dist

workflows:
  build-and-test:
    jobs:
      - build
