version: 2.1
orbs:
  codecov: codecov/codecov@3
executors:
  docker-executor:
    docker:
      - image: cimg/node:lts-browsers

jobs:
  build:
    executor: docker-executor
    environment:
      LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          command: |
            node -v
            npm -v
      - run:
          name: Update Yarn
          command: npm install -g npm@latest && npm install -g --force yarn@latest
      - restore-cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save-cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Run Tests
          command: yarn run ci:test
      - codecov/upload
      - store_artifacts:
          path: dist

workflows:
  build-and-test:
    jobs:
      - build
